In [ ]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
input_hidden_weights = np.array([[0.15, 0.2],
                                  [0.25, 0.3]])

hidden_output_weights = np.array([[0.4, 0.45],
                                  [0.55, 0.6]])

In [ ]:
print(hidden_output_weights)

[[0.4  0.45]
 [0.55 0.6 ]]


In [ ]:
print(input_hidden_weights)

[[0.15 0.2 ]
 [0.25 0.3 ]]


In [ ]:
X = np.array([[0.05],
              [0.1]])
print(X)

[[0.05]
 [0.1 ]]


In [ ]:
b1 = np.array([[0.35],
              [0.35]])

b2 = np.array([[0.6],
              [0.6]])

In [ ]:
hidden_layer_input = np.dot(input_hidden_weights,X) + b1
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_input = np.dot(hidden_output_weights,hidden_layer_output) + b2
predicted_output = sigmoid(output_layer_input)

print("Hidden Layer Calculations:")
print("Hidden Layer Input:")
print(hidden_layer_input)
print("\nHidden Layer Output:")
print(hidden_layer_output)

print("\nOutput Layer Calculations:")
print("Output Layer Input:")
print(output_layer_input)
print("\nPredicted Output:")
print(predicted_output)

Hidden Layer Calculations:
Hidden Layer Input:
[[0.3775]
 [0.3925]]

Hidden Layer Output:
[[0.5932699921]
 [0.5968843783]]

Output Layer Calculations:
Output Layer Input:
[[1.1059059671]
 [1.2844291226]]

Predicted Output:
[[0.7513650696]
 [0.7832027679]]
